#!/usr/bin/env python3
"""Compile the renderer's HLSL shaders (shaders/*.hlsl) for every SDL_GPU
backend and write them into src/app/shaders_gen.h, which is committed so a
build needs no shader tools:

  SPIR-V (Vulkan) and DXIL (Direct3D 12): Microsoft DXC
  MSL (Metal): SPIRV-Cross from the SPIR-V

  build_shaders.py [--dxc PATH] [--spirv-cross PATH]

DXC: dxc on PATH, or --dxc pointing at dxc / dxc.exe (a Windows dxc.exe runs
under Wine on Linux, which also signs the DXIL through dxil.dll next to it).
Run it after editing a shader and commit the regenerated header.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = ["poly.vert", "poly.frag", "composite.vert", "composite.frag"]


def dxc_cmd(dxc):
    if dxc.lower().endswith(".exe") and os.name != "nt":
        wine = shutil.which("wine64") or shutil.which("wine") or "/usr/lib/wine/wine64"
        return [wine, dxc]
    return [dxc]


def run(cmd):
    env = dict(os.environ, WINEDEBUG="-all")
    r = subprocess.run(cmd, capture_output=True, text=True, env=env)
    if r.returncode != 0:
        sys.exit(f"build_shaders: {' '.join(cmd)} failed:\n{r.stdout}{r.stderr}")


def array(name, data):
    lines = [f"inline constexpr unsigned char {name}[] = {{"]
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 20]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dxc", default=shutil.which("dxc") or "dxc")
    ap.add_argument("--spirv-cross", default=shutil.which("spirv-cross") or "spirv-cross")
    args = ap.parse_args()
    dxc = dxc_cmd(args.dxc)
    out = ["// Generated by scripts/build_shaders.py from shaders/*.hlsl: do not edit.",
           "// SPIR-V and DXIL from DXC, MSL from SPIRV-Cross; entry point main (MSL: main0).",
           "#pragma once", "", "namespace shaders {", ""]
    with tempfile.TemporaryDirectory() as tmp:
        for s in SHADERS:
            src = os.path.join(ROOT, "shaders", s + ".hlsl")
            profile = "vs_6_0" if s.endswith("vert") else "ps_6_0"
            ident = s.replace(".", "_")
            dxil, spv, msl = (os.path.join(tmp, s + e) for e in (".dxil", ".spv", ".msl"))
            run(dxc + ["-nologo", "-T", profile, "-E", "main", "-O3", src, "-Fo", dxil])
            run(dxc + ["-nologo", "-spirv", "-fspv-target-env=vulkan1.0", "-T", profile, "-E", "main", "-O3", src, "-Fo", spv])
            run([args.spirv_cross, "--msl", "--msl-version", "20100", "--msl-decoration-binding", spv, "--output", msl])
            for ext, path in (("spirv", spv), ("dxil", dxil), ("msl", msl)):
                with open(path, "rb") as f:
                    data = f.read()
                if ext == "msl":
                    data += b"\0"
                out.append(array(f"{ident}_{ext}", data))
                out.append("")
    out.append("} // namespace shaders")
    dest = os.path.join(ROOT, "src", "app", "shaders_gen.h")
    with open(dest, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"build_shaders: wrote {os.path.relpath(dest, ROOT)}")


if __name__ == "__main__":
    main()
